### ISSUE TITLE
我在步骤四困惑了

### ISSUE THREAD

**Issue by makeGHjk** [zCandy0/cctalk-downloader#2]
“4.获取cookie

切换到控制台选项卡，输入alert(document.cookie)即可弹出cookie”
在进行这一步时，我按照步骤，输入后并没有弹出cookie

**Comment by zCandy0** [comment]
![image](https://github.com/user-attachments/assets/611b2ed4-b922-4618-b07e-d4b3db4c8945)
这是执行的截图，请确认是否有操作失误
后续我将会为readme附上截图以便理解
