### ISSUE TITLE
下载不全

### ISSUE THREAD

**Issue by Diligent-wool** [zCandy0/cctalk-downloader#3]
不知道是不是因为课程视频受版权保护，只能下载开头的一部分视频，这个有什么办法可以解决吗？

**Comment by zCandy0** [comment]
正常来说，只要在线有观看权限的视频就能下载，可以确认一下网络环境，是不是网络波动导致没有下载完全，可以尝试重新下载，或者检查是否已经购买课程。如果还是不行，请提供具体信息。

**Comment by Diligent-wool** [comment]
可能是因为在线无法正常观看，只能在客户端正常观看吧

**Comment by zCandy0** [comment]
那就可能不行，我没有遇到过这种情况，所以无法处理
