### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by pawadali** [zCandy0/cctalk-downloader#4]
大佬你好！想问下这是什么情况，我不懂代码这些，也不知道我前面输入的两个对不对，不知道是哪里出错了，如果大佬允许，可以加个联系方式指导我一下吗？感谢！（qq：804075386@qq.com）
![2024年12 09日-21时12分-49 ](https://github.com/user-attachments/assets/ddf67100-fb52-49c8-a7a3-380a628654b8)

**Comment by zCandy0** [comment]
第二个输错了，后续我会加上错误处理，提供便于辨识的报错

**Comment by pawadali** [comment]
我是这样复制的，那正确输入要从哪里复制呢，![2024年12 09日-21时30分-52 ](https://github.com/user-attachments/assets/5a6030bb-715d-4bbe-a26f-3a555439d639)

**Comment by pawadali** [comment]
不太行，我跟之前发问题的那位一样，我把id输入正确后，网页提取出来的视频都是十几秒无法完整提取，我买的是付费课，估计就是平台版权机制导致的，网页上看不了，只能下载平台看，这个开启版权的视频就提取本来

**Comment by zCandy0** [comment]
我询问过周边的人，但是都没有购买过这样的课程，所以无法处理，暂时搁置
